framework:
    messenger:
        default_bus: command.bus
        buses:
            command.bus:
                default_middleware: false
                middleware:
                    - add_bus_name_stamp_middleware: [ 'command.bus' ]
                    - reject_redelivered_message_middleware
                    - App\Core\Infrastructure\MessageBus\Middleware\CommandStackingMiddleware
                    - dispatch_after_current_bus
                    - failed_message_processing_middleware
                    - doctrine_ping_connection
                    - doctrine_close_connection
                    - doctrine_transaction
                    - send_message
                    - App\Core\Infrastructure\MessageBus\Middleware\ValidationMiddleware
                    - App\Core\Infrastructure\MessageBus\Middleware\LockingMiddleware
                    - handle_message
            query.bus:

        transports:
            # https://symfony.com/doc/current/messenger.html#transport-configuration
            # async: '%env(MESSENGER_TRANSPORT_DSN)%'
            # failed: 'doctrine://default?queue_name=failed'
            # sync: 'sync://'

        routing:
            # 'App\Message\YourMessage': async
