controllers:
    resource:
        path: ../src/Controller/
        namespace: App\Controller
    type: attribute

user_controller:
    resource:
        path: ../src/User/Presentation/Controller
        namespace: App\User\Presentation\Controller
    type: attribute


api_login_check:
    path: /api/auth/login