parameters:

services:
    _defaults:
        autowire: true
        autoconfigure: true

    App\:
        resource: '../src/'
        exclude:
            - '../src/DependencyInjection/'
            - '../src/Entity/'
            - '../src/Kernel.php'

    App\Core\Application\Listener\KernelListener:
        tags:
            - { name: kernel.event_listener, event: kernel.request, priority: 0 }
